{
 "title": "jobinfo",
 "description": "Metrics collected by the jobinfo.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prom_ds", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_id",
    "label": "Job ID",
    "query": {
     "query": "label_values(cgroups_slurm_cpuacct_usage_per_cpu_ns, job_id)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(cgroups_slurm_cpuacct_usage_per_cpu_ns{job_id=\"$job_id\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "Percent Usage" }
   ],
   "targets": [
    {
     "expr": "sum by (cpu_id) (rate(cgroups_slurm_cpuacct_usage_per_cpu_ns{job_id=\"$job_id\",instance=~\"$node:.*\"}[$__rate_interval])/1e+9*100  * on(cpu_id,step_id,task_id,user_id) cgroups_slurm_cpuset_cpus{job_id=\"$job_id\",instance=~\"$node:.*\"})",
     "legendFormat": "CPU {{ cpu_id }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Memory Used (GB)" }
   ],
   "targets": [
    {
     "expr": "sum by (job_id) (cgroups_slurm_memory_usage_in_bytes{job_id=\"$job_id\",instance=~\"$node:.*\"}/1e+9)",
     "legendFormat": "Job {{ job_id }}"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "Percent Usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cgroups_slurm_cpuacct_usage_per_cpu_ns{job_id=\"$job_id\",instance=~\"$node:.*\"}[$__rate_interval]) * on(cpu_id,step_id,task_id,user_id) cgroups_slurm_cpuset_cpus{job_id=\"$job_id\",instance=~\"$node:.*\"})/(count(count by(cpu_id) (cgroups_slurm_cpuset_cpus{job_id=\"$job_id\",instance=~\"$node:.*\"}))*1e9)*100",
     "legendFormat": "Total CPU Usage"
    }
   ]
  },
  {
   "title": "Number of Allocated CPUs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(max by (cpu_id) (cgroups_slurm_cpuset_cpus{job_id=\"$job_id\",instance=~\"$node:.*\"}))",
     "legendFormat": "Number of Allocated CPUs"
    }
   ]
  }
 ]
}